/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author erik
 */
public class Consultas1 extends javax.swing.JFrame {

    /**
     * Creates new form Consultas1
     */
    public Consultas1() {
        initComponents();
        txtNumControl.setEnabled(false);
        txtNombre.setEnabled(false);
        txtPrimerAp.setEnabled(false);
        txtSegundoAp.setEnabled(false);
        comboEdad.setEnabled(false);
        comboSemestre.setEnabled(false);
        comboCarrera.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        ModificarInter = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtNumControl = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrimerAp = new javax.swing.JTextField();
        txtSegundoAp = new javax.swing.JTextField();
        comboEdad = new javax.swing.JComboBox<>();
        comboSemestre = new javax.swing.JComboBox<>();
        comboCarrera = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        radioNumControl = new javax.swing.JRadioButton();
        radioNombre = new javax.swing.JRadioButton();
        radioPrimerAp = new javax.swing.JRadioButton();
        radioSegundoAp = new javax.swing.JRadioButton();
        radioEdad = new javax.swing.JRadioButton();
        radioSemestre = new javax.swing.JRadioButton();
        radioCarrera = new javax.swing.JRadioButton();
        radioTodos = new javax.swing.JRadioButton();

        ModificarInter.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        ModificarInter.setVisible(true);

        jPanel1.setBackground(new java.awt.Color(36, 56, 245));

        jLabel1.setBackground(new java.awt.Color(229, 22, 22));
        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 48)); // NOI18N
        jLabel1.setText("Buscar Alumnos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        txtNumControl.setText("jTextField1");

        txtNombre.setText("jTextField2");

        txtPrimerAp.setText("jTextField3");

        txtSegundoAp.setText("jTextField4");

        comboEdad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jButton4.setText("Restablecer");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");

        buttonGroup2.add(radioNumControl);
        radioNumControl.setText("Numero de control");
        radioNumControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNumControlActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioNombre);
        radioNombre.setText("Nombre");
        radioNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioNombreActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioPrimerAp);
        radioPrimerAp.setText("Primer Apellido");
        radioPrimerAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioPrimerApActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioSegundoAp);
        radioSegundoAp.setText("Segundo Apellido");
        radioSegundoAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSegundoApActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioEdad);
        radioEdad.setText("Edad");
        radioEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioEdadActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioSemestre);
        radioSemestre.setText("Semestre");
        radioSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSemestreActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioCarrera);
        radioCarrera.setText("Carrera");
        radioCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCarreraActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioTodos);
        radioTodos.setText("Mostrar Todos");
        radioTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioTodosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioNumControl)
                    .addComponent(radioNombre)
                    .addComponent(radioPrimerAp)
                    .addComponent(radioSegundoAp)
                    .addComponent(radioEdad)
                    .addComponent(radioSemestre)
                    .addComponent(radioCarrera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrimerAp, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(txtNombre)
                    .addComponent(txtNumControl)
                    .addComponent(txtSegundoAp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(radioTodos)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioNumControl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioNombre)
                    .addComponent(radioTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrimerAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioPrimerAp))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSegundoAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioSegundoAp)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioEdad)
                    .addComponent(jButton4))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioSemestre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioCarrera))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ModificarInterLayout = new javax.swing.GroupLayout(ModificarInter.getContentPane());
        ModificarInter.getContentPane().setLayout(ModificarInterLayout);
        ModificarInterLayout.setHorizontalGroup(
            ModificarInterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ModificarInterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarInterLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        ModificarInterLayout.setVerticalGroup(
            ModificarInterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarInterLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 445, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(ModificarInterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ModificarInterLayout.createSequentialGroup()
                    .addGap(133, 133, 133)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(133, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ModificarInter)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ModificarInter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void radioNumControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNumControlActionPerformed
        // TODO add your handling code here:
        txtNumControl.setEnabled(true);
        txtNombre.setEnabled(false);
        txtPrimerAp.setEnabled(false);
        txtSegundoAp.setEnabled(false);
        comboEdad.setEnabled(false);
        comboSemestre.setEnabled(false);
        comboCarrera.setEnabled(false);
    }//GEN-LAST:event_radioNumControlActionPerformed

    private void radioEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioEdadActionPerformed
        // TODO add your handling code here:
        comboEdad.setEnabled(true);
        txtNumControl.setEnabled(false);
        txtNombre.setEnabled(false);
        txtPrimerAp.setEnabled(false);
        txtSegundoAp.setEnabled(false);
        comboSemestre.setEnabled(false);
        comboCarrera.setEnabled(false);
    }//GEN-LAST:event_radioEdadActionPerformed

    private void radioNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioNombreActionPerformed
        // TODO add your handling code here:
        txtNombre.setEnabled(true);
        txtNumControl.setEnabled(false);
        txtPrimerAp.setEnabled(false);
        txtSegundoAp.setEnabled(false);
        comboEdad.setEnabled(false);
        comboSemestre.setEnabled(false);
        comboCarrera.setEnabled(false);
    }//GEN-LAST:event_radioNombreActionPerformed

    private void radioPrimerApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioPrimerApActionPerformed
        // TODO add your handling code here:
        txtPrimerAp.setEnabled(true);
        txtNumControl.setEnabled(false);
        txtNombre.setEnabled(false);
        txtSegundoAp.setEnabled(false);
        comboEdad.setEnabled(false);
        comboSemestre.setEnabled(false);
        comboCarrera.setEnabled(false);
    }//GEN-LAST:event_radioPrimerApActionPerformed

    private void radioSegundoApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSegundoApActionPerformed
        // TODO add your handling code here:
        txtSegundoAp.setEnabled(true);
        txtNumControl.setEnabled(false);
        txtNombre.setEnabled(false);
        txtPrimerAp.setEnabled(false);
        comboEdad.setEnabled(false);
        comboSemestre.setEnabled(false);
        comboCarrera.setEnabled(false);
    }//GEN-LAST:event_radioSegundoApActionPerformed

    private void radioSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSemestreActionPerformed
        // TODO add your handling code here:
        comboSemestre.setEnabled(true);
        txtNumControl.setEnabled(false);
        txtNombre.setEnabled(false);
        txtPrimerAp.setEnabled(false);
        txtSegundoAp.setEnabled(false);
        comboEdad.setEnabled(false);
        comboCarrera.setEnabled(false);
    }//GEN-LAST:event_radioSemestreActionPerformed

    private void radioCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCarreraActionPerformed
        // TODO add your handling code here:
        comboCarrera.setEnabled(true);
        txtNumControl.setEnabled(false);
        txtNombre.setEnabled(false);
        txtPrimerAp.setEnabled(false);
        txtSegundoAp.setEnabled(false);
        comboEdad.setEnabled(false);
        comboSemestre.setEnabled(false);
    }//GEN-LAST:event_radioCarreraActionPerformed

    private void radioTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioTodosActionPerformed
        // TODO add your handling code here:
        txtNumControl.setEnabled(true);
        txtNombre.setEnabled(true);
        txtPrimerAp.setEnabled(true);
        txtSegundoAp.setEnabled(true);
        comboEdad.setEnabled(true);
        comboSemestre.setEnabled(true);
        comboCarrera.setEnabled(true);
    }//GEN-LAST:event_radioTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultas1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultas1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JInternalFrame ModificarInter;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> comboCarrera;
    private javax.swing.JComboBox<String> comboEdad;
    private javax.swing.JComboBox<String> comboSemestre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radioCarrera;
    private javax.swing.JRadioButton radioEdad;
    private javax.swing.JRadioButton radioNombre;
    private javax.swing.JRadioButton radioNumControl;
    private javax.swing.JRadioButton radioPrimerAp;
    private javax.swing.JRadioButton radioSegundoAp;
    private javax.swing.JRadioButton radioSemestre;
    private javax.swing.JRadioButton radioTodos;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumControl;
    private javax.swing.JTextField txtPrimerAp;
    private javax.swing.JTextField txtSegundoAp;
    // End of variables declaration//GEN-END:variables
}
